//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34003.
// 
#pragma warning disable 1591

namespace OfficeWorks.OWOffice.COMMONWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CommonSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FilterBaseClass))]
    public partial class Common : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetOrganizationalUnitsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBasicOrganizationalUnitsByRegistryBookOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Common() {
            this.Url = "http://localhost/OfficeWorks/WebServices/OWprocess/common.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetOrganizationalUnitsCompletedEventHandler GetOrganizationalUnitsCompleted;
        
        /// <remarks/>
        public event GetBasicOrganizationalUnitsByRegistryBookCompletedEventHandler GetBasicOrganizationalUnitsByRegistryBookCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrganizationalUnits", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BasicOrganizationalUnit[] GetOrganizationalUnits(OrganizationalUnitFilter filter) {
            object[] results = this.Invoke("GetOrganizationalUnits", new object[] {
                        filter});
            return ((BasicOrganizationalUnit[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetOrganizationalUnits(OrganizationalUnitFilter filter, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOrganizationalUnits", new object[] {
                        filter}, callback, asyncState);
        }
        
        /// <remarks/>
        public BasicOrganizationalUnit[] EndGetOrganizationalUnits(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BasicOrganizationalUnit[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOrganizationalUnitsAsync(OrganizationalUnitFilter filter) {
            this.GetOrganizationalUnitsAsync(filter, null);
        }
        
        /// <remarks/>
        public void GetOrganizationalUnitsAsync(OrganizationalUnitFilter filter, object userState) {
            if ((this.GetOrganizationalUnitsOperationCompleted == null)) {
                this.GetOrganizationalUnitsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrganizationalUnitsOperationCompleted);
            }
            this.InvokeAsync("GetOrganizationalUnits", new object[] {
                        filter}, this.GetOrganizationalUnitsOperationCompleted, userState);
        }
        
        private void OnGetOrganizationalUnitsOperationCompleted(object arg) {
            if ((this.GetOrganizationalUnitsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrganizationalUnitsCompleted(this, new GetOrganizationalUnitsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBasicOrganizationalUnitsByRegistryBook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BasicOrganizationalUnit[] GetBasicOrganizationalUnitsByRegistryBook(int bookID) {
            object[] results = this.Invoke("GetBasicOrganizationalUnitsByRegistryBook", new object[] {
                        bookID});
            return ((BasicOrganizationalUnit[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetBasicOrganizationalUnitsByRegistryBook(int bookID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetBasicOrganizationalUnitsByRegistryBook", new object[] {
                        bookID}, callback, asyncState);
        }
        
        /// <remarks/>
        public BasicOrganizationalUnit[] EndGetBasicOrganizationalUnitsByRegistryBook(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BasicOrganizationalUnit[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBasicOrganizationalUnitsByRegistryBookAsync(int bookID) {
            this.GetBasicOrganizationalUnitsByRegistryBookAsync(bookID, null);
        }
        
        /// <remarks/>
        public void GetBasicOrganizationalUnitsByRegistryBookAsync(int bookID, object userState) {
            if ((this.GetBasicOrganizationalUnitsByRegistryBookOperationCompleted == null)) {
                this.GetBasicOrganizationalUnitsByRegistryBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBasicOrganizationalUnitsByRegistryBookOperationCompleted);
            }
            this.InvokeAsync("GetBasicOrganizationalUnitsByRegistryBook", new object[] {
                        bookID}, this.GetBasicOrganizationalUnitsByRegistryBookOperationCompleted, userState);
        }
        
        private void OnGetBasicOrganizationalUnitsByRegistryBookOperationCompleted(object arg) {
            if ((this.GetBasicOrganizationalUnitsByRegistryBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBasicOrganizationalUnitsByRegistryBookCompleted(this, new GetBasicOrganizationalUnitsByRegistryBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrganizationalUnitFilter : FilterBaseClass {
        
        private int organizationalUnitTypeField;
        
        private string descriptionField;
        
        private DBBool activeField;
        
        private bool onlyFavoritesField;
        
        /// <remarks/>
        public int OrganizationalUnitType {
            get {
                return this.organizationalUnitTypeField;
            }
            set {
                this.organizationalUnitTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public DBBool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public bool OnlyFavorites {
            get {
                return this.onlyFavoritesField;
            }
            set {
                this.onlyFavoritesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DBBool {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BasicOrganizationalUnit {
        
        private int idField;
        
        private string descriptionField;
        
        private OrganizationalUnitTypeEnum typeField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public OrganizationalUnitTypeEnum Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum OrganizationalUnitTypeEnum {
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        User,
        
        /// <remarks/>
        Group,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganizationalUnitFilter))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FilterBaseClass {
        
        private int pageNumberField;
        
        private int pageSizeField;
        
        private string sortFieldField;
        
        private SortDirectionEnum sortDirectionField;
        
        private bool filteredField;
        
        /// <remarks/>
        public int PageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        public string SortField {
            get {
                return this.sortFieldField;
            }
            set {
                this.sortFieldField = value;
            }
        }
        
        /// <remarks/>
        public SortDirectionEnum SortDirection {
            get {
                return this.sortDirectionField;
            }
            set {
                this.sortDirectionField = value;
            }
        }
        
        /// <remarks/>
        public bool Filtered {
            get {
                return this.filteredField;
            }
            set {
                this.filteredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SortDirectionEnum {
        
        /// <remarks/>
        Ascending,
        
        /// <remarks/>
        Descending,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetOrganizationalUnitsCompletedEventHandler(object sender, GetOrganizationalUnitsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrganizationalUnitsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrganizationalUnitsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BasicOrganizationalUnit[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BasicOrganizationalUnit[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetBasicOrganizationalUnitsByRegistryBookCompletedEventHandler(object sender, GetBasicOrganizationalUnitsByRegistryBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBasicOrganizationalUnitsByRegistryBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBasicOrganizationalUnitsByRegistryBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BasicOrganizationalUnit[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BasicOrganizationalUnit[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591